name: card_expand_drawer
description: >-
  CardExpandDrawer is a UI widget package. Consists of a card widget
  which obstructs a drawer widget underneath. Upon swiping the card it reveals the drawer
  widget. This only handles the setup and swipe animations, all widgets for card and drawer
  are user provided.

version: 0.3.0-beta
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_hooks: ^0.18.4
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.21.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: