name: super_card_drawer
description: 
  Super Card Drawer is a collection of packages that help making swipe to reveal drawers trivial.
version: 0.3.0-beta
homepage: https://github.com/parkerhutchinson/super_card_drawer


environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter_hooks: ^0.18.4
  flutter:
    sdk: flutter

dependency_overrides:
  card_reveal_drawer: 
    path: ../card_reveal_drawer
  card_expand_drawer:
    path: ../card_expand_drawer

dev_dependencies:
  test: ^1.21.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: